spring:
  datasource:
    url: postgres://${PROD_DB_USERNAME}:${PROD_DB_PASSWORD}@${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: spring-blog

  sql:
    init:
      mode: always # won't do this in prod

server:
  servlet:
    contextPath: "/api"